"""
app/models/panchang.py
──────────────────────
Beanie Document model for the `panchang` MongoDB collection.

What is a Panchang?
  The Panchang (Sanskrit: पञ्चाङ्ग, "five limbs") is the traditional Hindu
  lunisolar almanac.  Its five elements are:
    1. Tithi     – Lunar day (1–30), each ~23 h 37 min long.
    2. Vara      – Day of the week (named after planets).
    3. Nakshatra – Lunar mansion (~13.3° arc of the ecliptic).
    4. Yoga      – A combined Sun+Moon longitude measure (27 types).
    5. Karana    – Half of a Tithi (11 types).

Dharma AI's angle:
  Every panchang entry includes `inferences` — a list of modern scientific
  or biological observations that correlate with the cosmic state.
  Example: during a Purnamasi (full moon) Tithi, studies have linked
  heightened tidal gravitational forces to disrupted sleep and increased
  emergency-room admissions.  These ground the ancient calendar in
  observable reality for skeptical users.

Indexing:
  A compound unique index on (date, city) prevents duplicate entries and
  enables O(1) lookups for the GET /cosmic endpoint.
"""

from datetime import date
from typing import Annotated, List

from beanie import Document, Indexed
from pydantic import Field
from pymongo import ASCENDING, IndexModel


class DailyPanchang(Document):
    """
    Pre-calculated daily Panchang snapshot for a specific city and date.

    Data should be populated by a scheduled cron job (e.g., Azure Functions
    Timer trigger) that runs nightly and inserts the next day's data for
    all supported cities.
    """

    # ── Primary lookup key ────────────────────────────────────────────────────
    date: Annotated[date, Indexed()]
    city: Annotated[str, Indexed()]

    # ── The Five Limbs (Pancha Anga) ──────────────────────────────────────────
    tithi: str = Field(
        ...,
        description=(
            "Lunar day name.  Example: 'Tritiya' (3rd lunar day).  "
            "Each tithi is ~23 h 37 min; two tithis may occur in one solar day."
        ),
    )
    tithi_end: str = Field(
        ...,
        description="Local time at which the current tithi ends.  Format: HH:MM.",
    )

    nakshatra: str = Field(
        ...,
        description=(
            "Lunar mansion (one of 27).  The Moon transits each nakshatra "
            "in ~1 day.  Example: 'Rohini' — associated with fertility and growth."
        ),
    )
    nakshatra_end: str = Field(
        ...,
        description="Local time at which the current nakshatra ends.  Format: HH:MM.",
    )

    vaar: str = Field(
        ...,
        description=(
            "Sanskrit weekday.  Named after celestial bodies: "
            "Ravivaar (Sun), Somavaar (Moon), Mangalavaar (Mars), "
            "Budhavaar (Mercury), Guruvaar (Jupiter), "
            "Shukravaar (Venus), Shanivaar (Saturn)."
        ),
    )

    yoga: str = Field(
        ...,
        description=(
            "One of 27 Panchang yogas, calculated from the combined longitude "
            "of the Sun and Moon.  Example: 'Siddha' — historically auspicious "
            "for beginning new ventures."
        ),
    )

    karana: str = Field(
        ...,
        description="Half-tithi element (one of 11 types).  Example: 'Bava'.",
    )
    karana_end: str = Field(
        ...,
        description="Local time at which the current karana ends.  Format: HH:MM.",
    )

    paksha: str = Field(
        ...,
        description=(
            "'Shukla Paksha' (waxing fortnight, new → full moon) or "
            "'Krishna Paksha' (waning fortnight, full → new moon)."
        ),
    )

    # ── Scientific / Biological Inferences ────────────────────────────────────
    inferences: List[str] = Field(
        default_factory=list,
        description=(
            "A list of evidence-based observations that correlate with today's "
            "cosmic state.  Generated by the AI engine or pre-populated by "
            "subject-matter experts.  These are Dharma AI's key differentiator "
            "for skeptic users.  "
            "Example: ['Full moon gravitational pull increases interstitial fluid "
            "pressure; consider lighter meals and adequate hydration today.']"
        ),
    )

    class Settings:
        name = "panchang"
        indexes = [
            # Compound unique index: one record per city+date combination.
            IndexModel(
                [("date", ASCENDING), ("city", ASCENDING)],
                unique=True,
            ),
        ]
